@startuml
class DialogueLoader {
    Start() : void
    + LoadSaveDefault() : void
    + LoadSaveOne() : void
    + LoadSaveTwo() : void
    + LoadSaveThree() : void
}
MonoBehaviour <|-- DialogueLoader
@enduml
