@startuml
class DialogueSystem {
    + observerStage : int
    + greetingBotStage : int
    + missionControlStage : int
    Start() : void
    Update() : void
    DialogueChoice(character:string) : void
    + loadNewDialogue() : void
    + readTextFile(filePath:string) : string[]
}
class "List`1"<T> {
}
MonoBehaviour <|-- DialogueSystem
DialogueSystem --> "player" PlayerController
DialogueSystem --> "parser" Parser
DialogueSystem --> "instance" DialogueSystem
DialogueSystem --> "characterName" TextMeshProUGUI
DialogueSystem --> "displayText" TextMeshProUGUI
DialogueSystem --> "choice1Text" TextMeshProUGUI
DialogueSystem --> "choice2Text" TextMeshProUGUI
DialogueSystem --> "characterStage<int>" "List`1"
DialogueSystem --> "replyOptions<string>" "List`1"
DialogueSystem --> "replyStage<int>" "List`1"
DialogueSystem --> "characterIdentity<string>" "List`1"
DialogueSystem --> "observerDialogue<Dialogue>" "List`1"
DialogueSystem --> "greetingBotDialogue<Dialogue>" "List`1"
DialogueSystem --> "missionControlDialogue<Dialogue>" "List`1"
DialogueSystem --> "parsedDialogue<Dialogue>" "List`1"
DialogueSystem --> "previewedparsedDialogueFile<Dialogue>" "List`1"
@enduml
