@startuml
class DialogueDisplay {
    Start() : void
    Update() : void
}
MonoBehaviour <|-- DialogueDisplay
DialogueDisplay --> "characterName" GameObject
DialogueDisplay --> "player" PlayerController
@enduml
